
spring:
  kafka:
  #kafka服务地址 可以配置多个
    bootstrap-servers:
      - 127.0.0.1:9092
    #默认监听主题
    template:
      default-topic: test
    #自定义监听主题
    topic-name: test
    consumer:
      #auto-commit-interval: 5000 #自动提交消费位移时间隔时间
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #max-poll-records: 500 #批量消费每次最多消费多少条消息
      #enable-auto-commit: true #开启自动提交消费位移
      #auto-offset-reset: latest #其他earliest、none
      group-id: kafka.consumer.group #消费者组名称
      #client-id: kafka.consumer.client.id #消费者客户端ID
      #fetch-min-size: 1 #最小消费字节数
